name: json_dynamic_widget_plugin_charts_flutter
description: A plugin to the JSON Dynamic Widget to provide support for Google's Flutter Chargs
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_charts_flutter

version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  charts_flutter: ^0.12.0
  child_builder: ^2.0.0+1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_class: ^2.1.1
  json_dynamic_widget: ^3.5.1
  json_theme: ^3.2.0
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5

# dependency_overrides:
#   json_dynamic_widget:
#     path: ../json_dynamic_widget

dev_dependencies:
  flutter_test:
    sdk: flutter
