name: json_dynamic_widget_plugin_charts_flutter
description: A plugin to the JSON Dynamic Widget to provide support for Google's Flutter Charts
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_charts_flutter

version: 3.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

analyzer:
  exclude: [lib/generated/**]

dependencies:
  charts_common: ^0.12.0
  charts_flutter: ^0.12.0
  child_builder: ^2.0.0+3
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_dynamic_widget: ^5.0.0
  json_path: ^0.4.0
  json_theme: ^4.0.0
  logging: ^1.0.1
  meta: ^1.7.0
  uuid: ^3.0.6

# dependency_overrides:
#   json_dynamic_widget:
#     path: ../json_dynamic_widget

false_secrets:
  - example/web/index.html

dev_dependencies:
  flutter_test:
    sdk: flutter

ignore_updates:
  # Ignoring everything in flutter_test as those are all point-in-time entries
  # can't upgrade without upgrading Flutter itself.
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
