name: json_dynamic_widget_plugin_charts_flutter
description: A plugin to the JSON Dynamic Widget to provide support for Google's Flutter Charts
homepage: https://github.com/peiffer-innovations/json_dynamic_widget_plugin_charts_flutter

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  charts_common: ^0.12.0
  charts_flutter: ^0.12.0
  child_builder: ^2.0.0+2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_class: ^2.1.2+3
  json_dynamic_widget: ^3.6.0+2
  json_path: ^0.3.1
  json_theme: ^3.2.4
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5

# dependency_overrides:
#   json_class:
#     path: ../json_class
#   json_dynamic_widget:
#     path: ../json_dynamic_widget

false_secrets:
  - example/web/index.html

dev_dependencies:
  flutter_test:
    sdk: flutter
