name: 'json_dynamic_widget_plugin_charts_flutter'
description: "A plugin to the JSON Dynamic Widget to provide support for Google's Flutter Charts"
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_plugin_charts_flutter'
version: '3.0.0+28'

environment: 
  sdk: '>=2.18.0 <3.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'


dependencies: 
  child_builder: '^2.0.0+3'
  community_charts_common: '^1.0.0'
  community_charts_flutter: '^1.0.0'
  flutter: 
    sdk: 'flutter'
  intl: '^0.18.0'
  json_class: '^2.1.4'
  json_dynamic_widget: '^5.1.6+4'
  json_path: '^0.4.2'
  json_theme: '^4.0.3+3'
  logging: '^1.1.0'
  meta: '^1.8.0'
  uuid: '^3.0.7'

dependency_overrides: 
  intl: '^0.18.0'

false_secrets: 
  - 'example/web/index.html'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
