import 'all.dart';

export 'all.dart';

class JsonChartsFlutterSchemas {
  static final enums = {
    AnnotationLabelAnchorSchema.id: AnnotationLabelAnchorSchema.schema,
    AnnotationLabelDirectionSchema.id: AnnotationLabelDirectionSchema.schema,
    AnnotationLabelPositionSchema.id: AnnotationLabelPositionSchema.schema,
    ArcLabelPositionSchema.id: ArcLabelPositionSchema.schema,
    AxisDirectionSchema.id: AxisDirectionSchema.schema,
    BarGroupingTypeSchema.id: BarGroupingTypeSchema.schema,
    BarLabelAnchorSchema.id: BarLabelAnchorSchema.schema,
    BarLabelPlacementSchema.id: BarLabelPlacementSchema.schema,
    BarLabelPositionSchema.id: BarLabelPositionSchema.schema,
    BarLabelVerticalPositionSchema.id: BarLabelVerticalPositionSchema.schema,
    BehaviorPositionSchema.id: BehaviorPositionSchema.schema,
    DateTimeFactorySchema.id: DateTimeFactorySchema.schema,
    FillPatternTypeSchema.id: FillPatternTypeSchema.schema,
    InsideJustificationSchema.id: InsideJustificationSchema.schema,
    LegendDefaultMeasureSchema.id: LegendDefaultMeasureSchema.schema,
    LinePointHighlighterFollowLineTypeSchema.id:
        LinePointHighlighterFollowLineTypeSchema.schema,
    OutsideJustificationSchema.id: OutsideJustificationSchema.schema,
    PercentInjectorTotalTypeSchema.id: PercentInjectorTotalTypeSchema.schema,
    PointSymbolRendererSchema.id: PointSymbolRendererSchema.schema,
    RangeAnnotationAxisTypeSchema.id: RangeAnnotationAxisTypeSchema.schema,
    SelectionModeSchema.id: SelectionModeSchema.schema,
    SelectionModelTypeSchema.id: SelectionModelTypeSchema.schema,
    SelectionTriggerSchema.id: SelectionTriggerSchema.schema,
    SliderHandlePositionSchema.id: SliderHandlePositionSchema.schema,
    TickLabelAnchorSchema.id: TickLabelAnchorSchema.schema,
    TickLabelJustificationSchema.id: TickLabelJustificationSchema.schema,
  };

  static final objects = {
    AnnotationSegmentSchema.id: AnnotationSegmentSchema.schema,
    ArcLabelDecoratorSchema.id: ArcLabelDecoratorSchema.schema,
    ArcLabelLeaderLineStyleSpecSchema.id:
        ArcLabelLeaderLineStyleSpecSchema.schema,
    ArcRendererConfigSchema.id: ArcRendererConfigSchema.schema,
    AxisSpecSchema.id: AxisSpecSchema.schema,
    BarChartSchema.id: BarChartSchema.schema,
    BarRendererConfigSchema.id: BarRendererConfigSchema.schema,
    BarRendererDecoratorSchema.id: BarRendererDecoratorSchema.schema,
    BarTargetLineRendererConfigSchema.id:
        BarTargetLineRendererConfigSchema.schema,
    BucketingAxisSpecSchema.id: BucketingAxisSpecSchema.schema,
    ChartBehaviorSchema.id: ChartBehaviorSchema.schema,
    ChartTitleDirectionSchema.id: ChartTitleDirectionSchema.schema,
    ChartTitleSchema.id: ChartTitleSchema.schema,
    CornerStrategySchema.id: CornerStrategySchema.schema,
    DateTimeExtentsSchema.id: DateTimeExtentsSchema.schema,
    DatumLegendSchema.id: DatumLegendSchema.schema,
    DateTimeTickProviderSpecSchema.id: DateTimeTickProviderSpecSchema.schema,
    DomainHighlighterSchema.id: DomainHighlighterSchema.schema,
    EndPointsTimeAxisSpecSchema.id: EndPointsTimeAxisSpecSchema.schema,
    InitialHintBehaviorSchema.id: InitialHintBehaviorSchema.schema,
    InitialSelectionSchema.id: InitialSelectionSchema.schema,
    LayoutConfigSchema.id: LayoutConfigSchema.schema,
    LineChartSchema.id: LineChartSchema.schema,
    LinePointHighlighterSchema.id: LinePointHighlighterSchema.schema,
    LineRendererConfigSchema.id: LineRendererConfigSchema.schema,
    LineStyleSpecSchema.id: LineStyleSpecSchema.schema,
    MarginSpecSchema.id: MarginSpecSchema.schema,
    MaxWidthStrategySchema.id: MaxWidthStrategySchema.schema,
    NumericAxisSpecSchema.id: NumericAxisSpecSchema.schema,
    NumericComboChartSchema.id: NumericComboChartSchema.schema,
    NumericExtentsSchema.id: NumericExtentsSchema.schema,
    NumericTickProviderSpecSchema.id: NumericTickProviderSpecSchema.schema,
    OrdinalAxisSpecSchema.id: OrdinalAxisSpecSchema.schema,
    OrdinalComboChartSchema.id: OrdinalComboChartSchema.schema,
    OrdinalTickProviderSpecSchema.id: OrdinalTickProviderSpecSchema.schema,
    OrdinalViewportSchema.id: OrdinalViewportSchema.schema,
    PanAndZoomBehaviorSchema.id: PanAndZoomBehaviorSchema.schema,
    PercentAxisSpecSchema.id: PercentAxisSpecSchema.schema,
    PercentInjectorSchema.id: PercentInjectorSchema.schema,
    PieChartSchema.id: PieChartSchema.schema,
    PointRendererConfigSchema.id: PointRendererConfigSchema.schema,
    PointRendererDecoratorSchema.id: PointRendererDecoratorSchema.schema,
    RangeAnnotationSchema.id: RangeAnnotationSchema.schema,
    RenderSpecSchema.id: RenderSpecSchema.schema,
    RTLSpecSchema.id: RTLSpecSchema.schema,
    SelectNearestSchema.id: SelectNearestSchema.schema,
    SelectionModelSchema.id: SelectionModelSchema.schema,
    SeriesDatumConfigSchema.id: SeriesDatumConfigSchema.schema,
    SeriesLegendSchema.id: SeriesLegendSchema.schema,
    SeriesListSchema.id: SeriesListSchema.schema,
    SeriesRendererConfigSchema.id: SeriesRendererConfigSchema.schema,
    SeriesSchema.id: SeriesSchema.schema,
    SliderSchema.id: SliderSchema.schema,
    SliderStyleSchema.id: SliderStyleSchema.schema,
    SlidingViewportSchema.id: SlidingViewportSchema.schema,
    SymbolAnnotationRendererConfigSchema.id:
        SymbolAnnotationRendererConfigSchema.schema,
    SymbolRendererSchema.id: SymbolRendererSchema.schema,
    TextStyleSpecSchema.id: TextStyleSpecSchema.schema,
    TickFormatterSpecSchema.id: TickFormatterSpecSchema.schema,
    TickSpecSchema.id: TickSpecSchema.schema,
    TimeFormatterSpecSchema.id: TimeFormatterSpecSchema.schema,
    TimeSeriesChartSchema.id: TimeSeriesChartSchema.schema,
  };
}
