# name: Flutter Pull Request Checker

# on:
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"

#       - name: Validate
#         uses: peiffer-innovations/actions-flutter-validate@v1.1.1
#         with:
#           flutter_package: true
